---
- name: Configure latest version of TeamSpeak 3 server
  hosts: teamspeak
  become: yes
  become_method: sudo
  roles:
    - teamspeak
  handlers:
  - name: 'restart {{ ts_service }}'
    systemd:
      name: '{{ ts_service | default("ts3server") }}'
      state: restarted