- name: 'restart {{ ts_service }}'
  systemd:
    name: '{{ ts_service | default("ts3server") }}'
    state: restarted

- name: report
  mail:
    to: '{{ ts_admin_email | default("root@localhost") }}'
    subject: Ansible report
    body: 'TeamSpeak 3 Server version {{ latest_determined.stdout }} on {{ inventory_hostname }} has been installed.'
  delegate_to: localhost